ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"

[traps]

[traps.transaction_frequency_trap]
path = "out/TransactionFrequencyTrap.sol/TransactionFrequencyTrap.json"
response_contract = "0x687EC8f66D66b1DAcDf78f695304dae7Bb41312C"
response_function = "respondCallback(uint256)"
collection_function = "collect()"
should_respond_function = "shouldRespond(bytes[])"
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 10
private_trap = true
whitelist = [
  "0xf217bd47581e231b35159b5b9adc6e51a6ba6ac3",
  "0xE56B1b8C59d9A14b8dbb4c2b649168cCDF5Cd320"
]
address = "0xeCbc896c94c4ba184c1888DF3A4DBeD3f92A4441"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

